keys:
  - &marrero age15xtsgcaeu6qxz7hfg3u7s87fcf0kn6dnlsltqmuufpczdjfth3pq7he7fw
  - &marrero age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd 
creation_rules:
  - path_regex: systems/[^/]+\.yaml$
    key_groups:
      - age:
        - *marrero
