keys:
  - &florian age1kxyjc77c6g52q6vzfaylwpw6yg05frsq9eucsjculrj728hdhycszmfdls
  - &florian age16kps5ny9k3f0r0qx6cz2767mytpuy04lhy90rztf000245t0uajs0yqvz0
  - &florian age1jhakcyv4ffehmcl6nm3d4z3ts3kp7yrkdtrg0jzcg9t8unyrgdyqhllwz9
creation_rules:
  - path_regex: systems/[^/]+\.yaml$
    key_groups:
      - age:
        - *florian
